name: Starcharts

on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate starcharts
    runs-on: ubuntu-latest
    steps:
      - uses: MaoLongLong/actions-starcharts@8a02621f35e876183d7101b583133403e0c11c02 # main
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          svg_path: images/starcharts.svg
          commit_message: "chore: auto update starcharts"
          stars_change: ${{ secrets.STARS_CHANGE }}
